### ISSUE TITLE
Fix auto refresh function on dashboard

### ISSUE THREAD

**Issue by heborras** [CosmicPi/cosmicpi-rpi_V1.5#12]
The function dosent show persistance. The page refreshes once, but at reload the box is not checked any more and the page stops refreshing.
Confirmed on: Firefox, Chrome, Edge

**Comment by lukicdarkoo** [comment]
Fixed. Please check https://github.com/CosmicPi/cosmicpi-rpi_V1.5/issues/16#issuecomment-390787347 for details.
