### ISSUE TITLE
Web data display frozen

### ISSUE THREAD

**Issue by pingud98** [CosmicPi/cosmicpi-rpi_V1.5#13]
Observed on the unit Markus has been using - the web display (graph + unix time) don't update. Persists when connected to GPS (valid lock) and also network. Date/time verified as correct on the Pi. Possibly something up with the interface? Or it could be the GPS readout in the arduino - I'll try flashing his unit with some new firmware when I get back to CERN next week.

**Comment by heborras** [comment]
How was the date/time confirmed?
Do you have an export of the database by chance?

If its the GPS pipe on the arduino, then the issue should be visible in the database. As well if its the interface the database could give a hint to what went wrong

**Comment by heborras** [comment]
@pingud98 Is this issue still on-going? I remember reading a mail that reflashing the arduino did the trick...

**Comment by pingud98** [comment]
Issue closed. New arduino firmware sorted it.
