### ISSUE TITLE
Fix IP addresses in static mode.

### ISSUE THREAD

**Issue by pingud98** [CosmicPi/cosmicpi-rpi_V1.5#4]
Make them match the stickers on the front of the box - 192.168.12.1

**Comment by heborras** [comment]
What did you do about this? Changed the DHCP config?

**Comment by pingud98** [comment]
I wrote a new dhcpcd.conf in the root of the package and copy it over in the second script. It changes the ip address from 10.0.0.1 to 192.168.12.1. For some reason the DHCP daemon seems to be broken now though.

**Comment by pingud98** [comment]
DHCPcd (dnsmasq.conf) is now fixed. DHCP server working.
